version: "3"

tasks:
  fmt:
    desc: Run gofmt on all files
    cmds:
      - gofmt -w .
  build:dev:
    desc: Build dev binary to ./giondev
    cmds:
      - go build -o ./giondev ./cmd/gion
  test:
    desc: Run tests
    cmds:
      - go test ./...
