version: "3"

tasks:
  fmt:
    desc: Run gofmt on all files
    cmds:
      - gofmt -w .
  build:dev:
    desc: Build dev binary to ./gwstdev
    cmds:
      - go build -o ./gwstdev ./cmd/gwst
  test:
    desc: Run tests
    cmds:
      - go test ./...
