version: "3"

tasks:
  fmt:
    desc: Run gofmt on all files
    cmds:
      - gofmt -w .
  build:dev:
    desc: Build dev binary to ./gwiacdev
    cmds:
      - go build -o ./gwiacdev ./cmd/gwiac
  test:
    desc: Run tests
    cmds:
      - go test ./...
