version: "3"

tasks:
  fmt:
    desc: Run gofmt on all files
    cmds:
      - gofmt -w .
  build:dev:
    desc: Build dev binary to ./gwsdev
    cmds:
      - go build -o ./gwsdev ./cmd/gws
  test:
    desc: Run tests
    cmds:
      - go test ./...
